# $FreeBSD$

PORTNAME=	libslack
PORTVERSION=	0.6
CATEGORIES=	
MASTER_SITES=	http://www.libslack.org/download/

MAINTAINER=	freebsd@mgwsoftware.com
COMMENT=	A UNIX/C library of general utilities for programmers with Slack

USES=	gmake


.include <bsd.port.mk>
