# $FreeBSD$

PORTNAME=	libslack
PORTVERSION=	0.6
CATEGORIES=	
MASTER_SITES=	http://www.libslack.org/download/

MAINTAINER=	freebsd@mgwsoftware.com
COMMENT=	Generic utility library for UNIX/C to make code easier on the eye

USES=	gmake


.include <bsd.port.mk>
