# Created by: Michael Williams <ports@mgwsoftware.com>
# $FreeBSD$

PORTNAME=	liberalcrimesquad
PORTVERSION=	4.07.0
CATEGORIES=	games
USE_GITHUB=     yes
GH_ACCOUNT=     Kamal-Sadek
GH_PROJECT=     Liberal-Crime-Squad
GH_TAGNAME=     ed44f9998d3d76971905bd2bfd50636e6136643d

MAINTAINER=     ports@mgwsoftware.com
COMMENT=        NCurses game centred around stopping a far-right government

LICENSE=	GPLv2

GNU_CONFIGURE=	yes
USES=		gmake iconv autoreconf
CONFIGURE_ARGS+=${ICONV_CONFIGURE_ARG}

.include <bsd.port.mk>
